#!/usr/bin/env bash
cd "$(dirname "$0")"
source ./script/setup.sh

# 1. It takes 300ms for cmd-help to generate. It's too long to run in build-debug.sh, that's why we ignore it
# 2. Grammar is not expected to change very often, that's why it's not regenerated by default
./generate.sh --ignore-xcodeproj --ignore-cmd-help
swift build "$@"
swift build --target AppBundleTests "$@" # swift build doesn't build test targets by default :(

rm -rf .debug && mkdir .debug
cp -r .build/debug/aerospace .debug
cp -r .build/debug/AeroSpaceApp .debug

# Sign with the stable self-signed identity if it exists, so the Accessibility grant survives
# rebuilds instead of being reset every time (see ./setup-debug-codesigning.sh). No-op otherwise.
DEBUG_SIGN_IDENTITY="AeroSpace Debug Self-Signed"
if security find-identity -v -p codesigning 2>/dev/null | grep -q "$DEBUG_SIGN_IDENTITY"; then
    codesign --force --sign "$DEBUG_SIGN_IDENTITY" .debug/AeroSpaceApp
    if [ -d .debug/AeroSpaceDebug.app ]; then
        cp -f .debug/AeroSpaceApp .debug/AeroSpaceDebug.app/Contents/MacOS/AeroSpaceApp
        codesign --force --sign "$DEBUG_SIGN_IDENTITY" .debug/AeroSpaceDebug.app
    fi
fi
