import Foundation

/// TOML string literal: single-quoted unless the value contains a single quote
func tomlString(_ value: String) -> String {
    if !value.contains("'") {
        return "'\(value)'"
    }
    var escaped = value
    escaped = escaped.replacingOccurrences(of: "\\", with: "\\\\")
    escaped = escaped.replacingOccurrences(of: "\"", with: "\\\"")
    return "\"\(escaped)\""
}

/// TOML key: bare if alphanumeric/dash/underscore, quoted otherwise
func tomlKey(_ key: String) -> String {
    let bareAllowed = key.allSatisfy { $0.isLetter || $0.isNumber || $0 == "-" || $0 == "_" }
    return bareAllowed && !key.isEmpty ? key : tomlString(key)
}

private func tomlCommandValue(_ commands: [String]) -> String {
    commands.count == 1
        ? tomlString(commands[0])
        : "[" + commands.map { tomlString($0) }.joined(separator: ", ") + "]"
}

func emitAeroToml(builder: AeroConfigBuilder, diagnostics: [ImportDiagnostic], sourceKind: String) -> String {
    var out: [String] = []
    out.append("# Generated by 'import-config \(sourceKind)'")
    out.append("# Docs: https://nikitabobko.github.io/AeroSpace/guide")
    out.append("")
    out.append("config-version = 2")
    out.append("")

    if builder.disableFlattenNormalization {
        out.append("# i3 doesn't flatten nested containers; disabled so the imported 'split' bindings work")
        out.append("enable-normalization-flatten-containers = false")
        out.append("enable-normalization-opposite-orientation-for-nested-containers = false")
        out.append("")
    }

    if !builder.startupCommands.isEmpty {
        out.append("after-startup-command = [")
        for cmd in builder.startupCommands {
            out.append("    \(tomlString(cmd)),")
        }
        out.append("]")
        out.append("")
    }

    if let ffm = builder.focusFollowsMouse {
        out.append("focus-follows-mouse.enabled = \(ffm)")
    }
    if let layout = builder.defaultLayout {
        out.append("default-root-container-layout = \(tomlString(layout))")
    }
    if let orientation = builder.defaultOrientation {
        out.append("default-root-container-orientation = \(tomlString(orientation))")
    }
    if let policy = builder.tilingPolicy {
        out.append("tiling-policy = \(tomlString(policy))")
    }
    if builder.focusFollowsMouse != nil || builder.defaultLayout != nil || builder.defaultOrientation != nil || builder.tilingPolicy != nil {
        out.append("")
    }

    if !builder.gapsInner.isEmpty || !builder.gapsOuter.isEmpty {
        out.append("[gaps]")
        for key in ["vertical", "horizontal"] {
            if let v = builder.gapsInner[key] { out.append("inner.\(key) = \(v)") }
        }
        for key in ["left", "bottom", "top", "right"] {
            if let v = builder.gapsOuter[key] { out.append("outer.\(key) = \(v)") }
        }
        out.append("")
    }

    if !builder.workspaceToMonitor.isEmpty {
        out.append("[workspace-to-monitor-force-assignment]")
        for (workspace, output) in builder.workspaceToMonitor {
            out.append("\(tomlKey(workspace)) = \(tomlString(output))")
        }
        out.append("")
    }

    if !builder.persistentWorkspaces.isEmpty {
        let list = builder.persistentWorkspaces.map { tomlString($0) }.joined(separator: ", ")
        out.append("persistent-workspaces = [\(list)]")
        out.append("")
    }

    if !builder.windowBorders.isEmpty {
        out.append("[window-borders]")
        out.append("enabled = true")
        for line in builder.windowBorders {
            out.append(line)
        }
        out.append("")
    }

    for rule in builder.detectionRules {
        out.append("[[window-detection-rules]]")
        for matcher in rule.matchers {
            out.append(matcher)
        }
        out.append("treat-as = \(tomlString(rule.treatAs))")
        out.append("")
    }

    for callback in builder.windowCallbacks {
        out.append("[[on-window-detected]]")
        for matcher in callback.matchers {
            out.append(matcher)
        }
        out.append("run = \(tomlCommandValue(callback.run))")
        out.append("")
    }

    for mode in builder.modeNames {
        let bindings = builder.bindings.filter { $0.mode == mode }
        // 'main' is mandatory even when empty; other modes only exist if they have bindings
        if bindings.isEmpty && mode != "main" { continue }
        out.append("[mode.\(tomlKey(mode)).binding]")
        var seen: Set<String> = []
        for binding in bindings {
            if !seen.insert(binding.key).inserted {
                out.append("# duplicate binding dropped: \(binding.key) = \(tomlCommandValue(binding.commands))")
                continue
            }
            out.append("\(tomlKey(binding.key)) = \(tomlCommandValue(binding.commands))")
        }
        out.append("")
    }

    let skipped = diagnostics.filter { $0.severity == .skipped }
    if !skipped.isEmpty {
        out.append("# ============================================================")
        out.append("# Lines from the \(sourceKind) config that don't apply on macOS")
        out.append("# ============================================================")
        for d in skipped {
            out.append("# line \(d.lineNumber): \(d.original)")
            out.append("#     ^ \(d.reason)")
        }
        out.append("")
    }

    return out.joined(separator: "\n")
}
