/// Maps Linux X11 WM_CLASS values (as they commonly appear in i3 'for_window [class=...]'
/// and Hyprland 'windowrulev2 class:' rules) to macOS bundle identifiers.
/// Data only - lookup is case-insensitive. Classes without a macOS counterpart fall back
/// to an app-name-regex matcher at the call site
let linuxAppClassToBundleId: [String: String] = [
    "firefox": "org.mozilla.firefox",
    "firefox-esr": "org.mozilla.firefox",
    "firefoxdeveloperedition": "org.mozilla.firefoxdeveloperedition",
    "librewolf": "org.mozilla.librewolf",
    "chromium": "com.google.Chrome",
    "chromium-browser": "com.google.Chrome",
    "google-chrome": "com.google.Chrome",
    "brave-browser": "com.brave.Browser",
    "vivaldi-stable": "com.vivaldi.Vivaldi",
    "opera": "com.operasoftware.Opera",
    "safari": "com.apple.Safari",
    "zen": "app.zen-browser.zen",
    "qutebrowser": "org.qutebrowser.qutebrowser",

    "alacritty": "org.alacritty",
    "kitty": "net.kovidgoyal.kitty",
    "wezterm": "com.github.wez.wezterm",
    "org.wezfurlong.wezterm": "com.github.wez.wezterm",
    "ghostty": "com.mitchellh.ghostty",
    "com.mitchellh.ghostty": "com.mitchellh.ghostty",
    "st-256color": "com.apple.Terminal",
    "urxvt": "com.apple.Terminal",
    "xterm": "com.apple.Terminal",
    "gnome-terminal": "com.apple.Terminal",
    "konsole": "com.apple.Terminal",
    "foot": "com.apple.Terminal",

    "code": "com.microsoft.VSCode",
    "code-oss": "com.microsoft.VSCode",
    "vscodium": "com.vscodium",
    "cursor": "com.todesktop.230313mzl4w4u92",
    "jetbrains-idea": "com.jetbrains.intellij",
    "jetbrains-idea-ce": "com.jetbrains.intellij.ce",
    "jetbrains-webstorm": "com.jetbrains.WebStorm",
    "jetbrains-pycharm": "com.jetbrains.pycharm",
    "jetbrains-goland": "com.jetbrains.goland",
    "jetbrains-clion": "com.jetbrains.CLion",
    "sublime_text": "com.sublimetext.4",
    "emacs": "org.gnu.Emacs",
    "gvim": "org.vim.MacVim",
    "neovide": "com.neovide.neovide",
    "zed": "dev.zed.Zed",

    "discord": "com.hnc.Discord",
    "slack": "com.tinyspeck.slackmacgap",
    "telegram-desktop": "com.tdesktop.Telegram",
    "telegramdesktop": "com.tdesktop.Telegram",
    "signal": "org.whispersystems.signal-desktop",
    "element": "im.riot.app",
    "whatsapp": "net.whatsapp.WhatsApp",
    "zoom": "us.zoom.xos",
    "thunderbird": "org.mozilla.thunderbird",

    "spotify": "com.spotify.client",
    "mpv": "io.mpv",
    "vlc": "org.videolan.vlc",
    "obs": "com.obsproject.obs-studio",
    "audacity": "org.audacityteam.audacity",

    "gimp": "org.gimp.gimp-2.10",
    "gimp-2.10": "org.gimp.gimp-2.10",
    "inkscape": "org.inkscape.Inkscape",
    "blender": "org.blenderfoundation.blender",
    "krita": "org.krita",
    "darktable": "org.darktable",

    "steam": "com.valvesoftware.steam",
    "libreoffice": "org.libreoffice.script",
    "obsidian": "md.obsidian",
    "notion": "notion.id",
    "1password": "com.1password.1password",
    "keepassxc": "org.keepassxc.keepassxc",
    "bitwarden": "com.bitwarden.desktop",
    "nautilus": "com.apple.finder",
    "org.gnome.nautilus": "com.apple.finder",
    "thunar": "com.apple.finder",
    "dolphin": "com.apple.finder",
    "pavucontrol": "com.apple.systempreferences",
    "transmission-gtk": "org.m0k.transmission",
    "transmission-qt": "org.m0k.transmission",
    "qbittorrent": "org.qbittorrent.qBittorrent",
]
